version: "3.8"
services:
  # Nginx servers
  nginx-backend:
    image: nginx
    container_name: prestabanconginxbackend-container
    restart: always
    ports:
      - 80:80
    volumes:
      - ./backend.conf:/etc/nginx/nginx.conf
    networks:
      - prestabancobackend-network
    depends_on:
      - spring1
      - spring2
      - spring3      
  nginx-frontend:
    image: nginx
    container_name: prestabanconginxfrontend-container
    restart: always
    ports:
      - 8070:8070
    volumes:
      - ./frontend.conf:/etc/nginx/nginx.conf
    networks:
      - prestabancofrontend-network
    depends_on:      
      - react1
      - react2
      - react3
  postgres:
    container_name: prestabancopostgres-container
    image: postgres
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - prestabancopostgres-volume:/var/lib/postgresql/data
    networks:
      - prestabancobackend-network
    environment:      
      POSTGRES_PASSWORD: postgres
    ports:
      - 5435:5432      
  spring1:
    container_name: prestabancobackend-container1
    image: benjasepulvedaflores/prestabancobackend
    ports:
      - 8091:8090
    environment:
      DB_HOST: prestabancopostgres-container
      DB_NAME: tingeso
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    networks:
      - prestabancobackend-network
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres
  spring2:
    container_name: prestabancobackend-container2
    image: benjasepulvedaflores/prestabancobackend
    ports:
      - 8092:8090
    environment:
      DB_HOST: prestabancopostgres-container
      DB_NAME: tingeso
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    networks:
      - prestabancobackend-network
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres
  spring3:
    container_name: prestabancobackend-container3
    image: benjasepulvedaflores/prestabancobackend
    ports:
      - 8093:8090
    environment:
      DB_HOST: prestabancopostgres-container
      DB_NAME: tingeso
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    networks:
      - prestabancobackend-network
    deploy:
      restart_policy:
        condition: on-failure
  react1:
    container_name: prestabancofrontend-container1
    image: benjasepulvedaflores/prestabancofrontend
    ports:
      - 3001:3000
    networks:
      - prestabancofrontend-network
    deploy:
      restart_policy:
        condition: on-failure
  react2:
    container_name: prestabancofrontend-container2
    image: benjasepulvedaflores/prestabancofrontend
    ports:
      - 3002:3000
    networks:
      - prestabancofrontend-network
    deploy:
      restart_policy:
        condition: on-failure
  react3:
    container_name: prestabancofrontend-container3
    image: benjasepulvedaflores/prestabancofrontend
    networks:
      - prestabancofrontend-network
    ports:
      - 3003:3000
    deploy:
      restart_policy:
        condition: on-failure
volumes:
  prestabancopostgres-volume:
networks:
  prestabancofrontend-network:
  prestabancobackend-network: